# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npx gulp copyAll && npx gulp compile

ports:
  - port: 8000
    onOpen: open-browser
